// Characterization fixtures for assembleWeek — self-contained, no imports
// from the test library so the pinned scenarios never drift with other tests.
// The expected outputs live in assembleWeek.characterization.expected.json,
// generated ONCE from the pre-move code: any behavioural change (including
// the _shared/ extraction) must reproduce them byte-for-byte.

import type { AssembleInput, CandidateRow } from "./assembleWeek.ts";
import type { ExerciseRow } from "./types.ts";

function row(
  partial: Partial<ExerciseRow> & { id: string; os_id: string; name: string },
): CandidateRow {
  return {
    exercise_family: "forza",
    movement_pattern: null,
    patterns: null,
    equipment: null,
    execution_mode: null,
    suited_rep_range: null,
    fatigue_cost: null,
    technical_complexity: null,
    laterality: "bilaterale",
    stability_demand: null,
    body_position: null,
    lift_phase: null,
    muscles: null,
    secondary_muscles: null,
    ...partial,
  };
}

/** Minimal-but-complete library: every pattern used by the 1-6 day splits. */
export const CHARACTERIZATION_LIBRARY: CandidateRow[] = [
  row({
    id: "fx-squat-1",
    os_id: "FX-101",
    name: "Back Squat",
    movement_pattern: "squat",
    equipment: ["bilanciere"],
    execution_mode: "grind",
    suited_rep_range: "forza",
    stability_demand: "bassa",
    muscles: ["quadricipiti", "glutei"],
  }),
  row({
    id: "fx-squat-2",
    os_id: "FX-102",
    name: "Goblet Squat",
    movement_pattern: "squat",
    equipment: ["manubri"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    stability_demand: "media",
    muscles: ["quadricipiti", "glutei"],
  }),
  row({
    id: "fx-hinge-1",
    os_id: "FX-103",
    name: "Romanian Deadlift",
    movement_pattern: "hip hinge",
    equipment: ["bilanciere"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["femorali", "glutei"],
  }),
  row({
    id: "fx-hinge-2",
    os_id: "FX-104",
    name: "Kettlebell Swing",
    exercise_family: "pliometrico",
    movement_pattern: "hip hinge",
    equipment: ["kettlebell"],
    execution_mode: "balistico",
    muscles: ["glutei", "femorali"],
  }),
  row({
    id: "fx-lunge-1",
    os_id: "FX-105",
    name: "Walking Lunge",
    movement_pattern: "lunge",
    equipment: ["manubri"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    laterality: "unilaterale",
    muscles: ["quadricipiti", "glutei"],
  }),
  row({
    id: "fx-push-h-1",
    os_id: "FX-106",
    name: "Bench Press",
    movement_pattern: "push orizzontale",
    equipment: ["bilanciere", "panca"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["pettorali"],
    secondary_muscles: ["spalle", "tricipiti"],
  }),
  row({
    id: "fx-push-h-2",
    os_id: "FX-107",
    name: "Push-Up",
    movement_pattern: "push orizzontale",
    equipment: ["corpo libero"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["pettorali"],
    secondary_muscles: ["tricipiti"],
  }),
  row({
    id: "fx-push-v-1",
    os_id: "FX-108",
    name: "Overhead Press",
    movement_pattern: "push verticale",
    equipment: ["bilanciere"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["spalle"],
  }),
  row({
    id: "fx-pull-h-1",
    os_id: "FX-109",
    name: "Barbell Row",
    movement_pattern: "pull orizzontale",
    equipment: ["bilanciere"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["dorsali"],
    secondary_muscles: ["bicipiti"],
  }),
  row({
    id: "fx-pull-h-2",
    os_id: "FX-110",
    name: "Dumbbell Row",
    movement_pattern: "pull orizzontale",
    equipment: ["manubri"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["dorsali"],
  }),
  row({
    id: "fx-pull-v-1",
    os_id: "FX-111",
    name: "Pull-Up",
    movement_pattern: "pull verticale",
    equipment: ["sbarra"],
    execution_mode: "grind",
    suited_rep_range: "entrambi",
    muscles: ["dorsali"],
  }),
  row({
    id: "fx-iso-1",
    os_id: "FX-112",
    name: "Biceps Curl",
    movement_pattern: "isolamento",
    equipment: ["manubri"],
    execution_mode: "grind",
    suited_rep_range: "ipertrofia",
    muscles: ["bicipiti"],
  }),
  row({
    id: "fx-core-ae-1",
    os_id: "FX-113",
    name: "Plank",
    movement_pattern: "core anti-estensione",
    equipment: ["corpo libero"],
    execution_mode: "isometrico",
    muscles: ["core"],
  }),
  row({
    id: "fx-core-ar-1",
    os_id: "FX-114",
    name: "Pallof Press",
    movement_pattern: "core anti-rotazione",
    equipment: ["cavi"],
    execution_mode: "isometrico",
    muscles: ["core"],
  }),
  row({
    id: "fx-carry-1",
    os_id: "FX-115",
    name: "Farmer's Carry",
    movement_pattern: "carry/locomozione",
    equipment: ["manubri"],
    execution_mode: "grind",
    muscles: ["core"],
    secondary_muscles: ["avambracci"],
  }),
];

/** Pinned scenarios: strength w/ 1RM + zones, hypertrophy defaults, 6-day limited gym. */
export const CHARACTERIZATION_SCENARIOS: { name: string; input: AssembleInput }[] = [
  {
    name: "forza-4d-1A-oneRm-zona-anca",
    input: {
      focusGoal: "forza",
      daysPerWeek: 4,
      equipmentRaw: "bilanciere, manubri, panca, sbarra, cavi, kettlebell, corpo libero",
      mode: "new",
      experienceLevel: "intermedio",
      trainingAge: null,
      neurotype: "1A",
      excludedZones: [{ zone: "anca", tier: "moderato" }],
      oneRmData: {
        "Back Squat": { estimated_1rm: 140 },
        "Bench Press": { estimated_1rm: 100 },
      },
      candidates: CHARACTERIZATION_LIBRARY,
    },
  },
  {
    name: "ipertrofia-3d-2B-default",
    input: {
      focusGoal: "ricomposizione corporea",
      daysPerWeek: 3,
      equipmentRaw: null,
      mode: "new",
      experienceLevel: "beginner",
      trainingAge: null,
      neurotype: "2B",
      excludedZones: [],
      oneRmData: null,
      candidates: CHARACTERIZATION_LIBRARY,
    },
  },
  {
    name: "forza-6d-3-spalla-aggressivo-equip-limitato",
    input: {
      focusGoal: "massimale",
      daysPerWeek: 6,
      equipmentRaw: "manubri e corpo libero",
      mode: "continue",
      experienceLevel: null,
      trainingAge: "7 anni di palestra",
      neurotype: "3",
      excludedZones: [{ zone: "spalla", tier: "aggressivo" }],
      oneRmData: null,
      candidates: CHARACTERIZATION_LIBRARY,
    },
  },
];
