/**
 * knip — dead code & unused export detector
 * --------------------------------------------------------------------------
 * Used by `npm run audit:dead`. See `.claude/methodology/05-DEAD-CODE-AUDIT.md`.
 *
 * Entry points: anything that bootstraps execution (browser, edge runtime,
 * test runner, config tooling). From these, knip walks the import graph to
 * find unreachable files / unused exports.
 */
import type { KnipConfig } from "knip";

const config: KnipConfig = {
  entry: [
    "src/main.tsx",
    "src/App.tsx",
    "supabase/functions/*/index.ts",
    "tests/**/*.spec.ts",
    "vite.config.ts",
    "tailwind.config.ts",
    "playwright.config.ts",
    "postcss.config.js",
    "eslint.config.js",
  ],
  project: ["src/**/*.{ts,tsx}", "supabase/functions/**/*.ts"],
  ignore: [
    // Auto-generated by Supabase/Lovable — periodically regenerated, do not flag
    "src/integrations/supabase/types.ts",
    // shadcn/ui primitives — kept available even if currently unused (future Stitch
    // implementations may pull in a Drawer, Menubar, etc.)
    "src/components/ui/**",
    // WIP feature modules — in PRODUCT_SPEC ma non ancora collegati a route/UI.
    // Tenuti di proposito (non sono dead code); ignorati perché gli audit non li
    // segnalino come orfani. ⚠️ RIVEDERE PRIMA DI OGNI RELEASE: vedi
    // docs/WIP_MODULES.md. Quando un modulo viene collegato, rimuovilo da qui; se
    // viene abbandonato, allora è dead code e va rimosso dal codebase.
    "src/hooks/usePeriodization.ts",
    "src/hooks/useCyclePhasing.ts",
    "src/hooks/useCoachTrainingBlocks.ts",
    "src/hooks/useCoachNutritionAnalytics.ts",
    "src/hooks/useAthleteHealthProfile.ts",
    "src/hooks/useFmsAlerts.ts",
    "src/hooks/useOfflineSync.ts",
    "src/hooks/useFeatureAccess.ts",
    "src/lib/math/readinessMath.ts",
    "src/lib/math/adaptiveTDEE.ts",
    "src/lib/math/biometrics.ts",
    "src/lib/math/nutritionMath.ts",
    "src/lib/math/constants.ts",
    "src/lib/offlineStorage.ts",
    "src/lib/media.ts",
    "src/lib/mediaSession.ts",
    "src/lib/imageCompression.ts",
    "src/services/foodApi.ts",
    "src/types/progression.ts",
    "src/types/database.ts",
  ],
  ignoreDependencies: [
    // Used implicitly via lint-staged config in package.json
    "husky",
    "lint-staged",
    "prettier",
    // Used only via npm scripts / tooling, not import graph
    "@playwright/test",
  ],
  ignoreBinaries: [
    // Some scripts call binaries that knip can't always trace
    "tsc",
  ],
};

export default config;
